import pygame

# ========================================== BULLET ENEMY SETUP ==========================================

###### Setup đạn level 1 của Enemy:
ENEMY_LEVEL_1_BULLET_WIDTH = 8
ENEMY_LEVEL_1_BULLET_HEIGHT = 20
ENEMY_LEVEL_1_BULLET_DELAY = 2000
ENEMY_LEVEL_1_BULLET_SPEED = 3
ENEMY_LEVEL_1_BULLET_COUNT = 1
ENEMY_LEVEL_1_BULLET_START_ANGLE = 0
ENEMY_LEVEL_1_BULLET_END_ANGLE = 0
ENEMY_LEVEL_1_BULLET_IMAGE = pygame.transform.scale(pygame.image.load("resources/images/Enemy_Level_1_Bullet.png"), (ENEMY_LEVEL_1_BULLET_WIDTH, ENEMY_LEVEL_1_BULLET_HEIGHT))

###### Setup đạn level 2 của Enemy:
ENEMY_LEVEL_2_BULLET_WIDTH = 12
ENEMY_LEVEL_2_BULLET_HEIGHT = 20
ENEMY_LEVEL_2_BULLET_DELAY = 1000
ENEMY_LEVEL_2_BULLET_SPEED = 5
ENEMY_LEVEL_2_BULLET_COUNT = 2
ENEMY_LEVEL_2_BULLET_START_ANGLE = -7
ENEMY_LEVEL_2_BULLET_END_ANGLE = 7
ENEMY_LEVEL_2_BULLET_IMAGE = pygame.transform.scale(pygame.image.load("resources/images/Enemy_Level_2_Bullet.png"), (ENEMY_LEVEL_2_BULLET_WIDTH, ENEMY_LEVEL_2_BULLET_HEIGHT))

###### Setup đạn level 3 của Enemy:
ENEMY_LEVEL_3_BULLET_WIDTH = 15
ENEMY_LEVEL_3_BULLET_HEIGHT = 40
ENEMY_LEVEL_3_BULLET_DELAY = 2000
ENEMY_LEVEL_3_BULLET_SPEED = 5
ENEMY_LEVEL_3_BULLET_COUNT = 3
ENEMY_LEVEL_3_BULLET_START_ANGLE = -20
ENEMY_LEVEL_3_BULLET_END_ANGLE = 20
ENEMY_LEVEL_3_BULLET_IMAGE = pygame.transform.scale(pygame.image.load("resources/images/Enemy_Level_3_Bullet.png"), (ENEMY_LEVEL_3_BULLET_WIDTH, ENEMY_LEVEL_3_BULLET_HEIGHT))

###### Setup đạn level 4 của Enemy:
ENEMY_LEVEL_4_BULLET_WIDTH = 10
ENEMY_LEVEL_4_BULLET_HEIGHT = 50
ENEMY_LEVEL_4_BULLET_DELAY = 3000
ENEMY_LEVEL_4_BULLET_SPEED = 5
ENEMY_LEVEL_4_BULLET_COUNT = 5
ENEMY_LEVEL_4_BULLET_START_ANGLE = -50
ENEMY_LEVEL_4_BULLET_END_ANGLE = 50
ENEMY_LEVEL_4_BULLET_IMAGE = pygame.transform.scale(pygame.image.load("resources/images/Enemy_Level_4_Bullet.png"), (ENEMY_LEVEL_4_BULLET_WIDTH, ENEMY_LEVEL_4_BULLET_HEIGHT))

###### Setup đạn level 5 của Enemy:
ENEMY_LEVEL_5_BULLET_WIDTH = 30
ENEMY_LEVEL_5_BULLET_HEIGHT = 30
ENEMY_LEVEL_5_BULLET_DELAY = 3000
ENEMY_LEVEL_5_BULLET_SPEED = 5
ENEMY_LEVEL_5_BULLET_COUNT = 10
ENEMY_LEVEL_5_BULLET_START_ANGLE = 0
ENEMY_LEVEL_5_BULLET_END_ANGLE = 360
ENEMY_LEVEL_5_BULLET_IMAGE = pygame.transform.scale(pygame.image.load("resources/images/Enemy_Level_5_Bullet.png"), (ENEMY_LEVEL_5_BULLET_WIDTH, ENEMY_LEVEL_5_BULLET_HEIGHT))

###### Danh sách đạn của Player:
ENEMY_LEVEL_1_BULLET_LIST = pygame.sprite.Group()
ENEMY_LEVEL_2_BULLET_LIST = pygame.sprite.Group()
ENEMY_LEVEL_3_BULLET_LIST = pygame.sprite.Group()
ENEMY_LEVEL_4_BULLET_LIST = pygame.sprite.Group()
ENEMY_LEVEL_5_BULLET_LIST = pygame.sprite.Group()